// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckConnection(arg1) {
  return window['go']['main']['App']['CheckConnection'](arg1);
}

export function CheckTagsFileExists() {
  return window['go']['main']['App']['CheckTagsFileExists']();
}

export function CreateTagsFileFromURL(arg1) {
  return window['go']['main']['App']['CreateTagsFileFromURL'](arg1);
}

export function GetDefaultTagsFileURL() {
  return window['go']['main']['App']['GetDefaultTagsFileURL']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function GetQRCodes() {
  return window['go']['main']['App']['GetQRCodes']();
}

export function GetSavedComfyUIURL() {
  return window['go']['main']['App']['GetSavedComfyUIURL']();
}

export function OpenSimpleComfyUI() {
  return window['go']['main']['App']['OpenSimpleComfyUI']();
}
