// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckConnection(arg1:string):Promise<main.ConnectResult>;

export function GetQRCode():Promise<main.QRCodeResult>;

export function GetQRCodes():Promise<main.QRCodeListResult>;

export function GetSavedComfyUIURL():Promise<string>;

export function OpenSimpleComfyUI():Promise<main.ConnectResult>;
